### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by tonmoy007** [ranacseruet/codeigniterplus#25]

**Comment by ranacseruet** [comment]
ok, closing then.

**Comment by tonmoy007** [comment]
hello sir
i have just installed your framework of codignitor plus. using your page
when i tried to login using facebook account it appears that my app id is
invalid ..
i am just a beginner in codignitor platform . can u help me how to solve
this and i can login with facebook id..

Thank you in advance
tonmoy

On Fri, May 8, 2015 at 11:11 AM, Md Ali Ahsan Rana <notifications@github.com
